server:
  port: 8104

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: stock-producer-group

spring:
  application:
    name: mall-stock-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        group: DEFAULT_GROUP
      config:
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
    function:
      definition: stockIn0
    stream:
      rocketmq:
        binder:
          name-server: ${rocketmq.name-server}
      bindings:
        #发送消息 输出通道
        stockOut0:
          destination: stock-event-topic
          content-type: application/json
        #接收消息 输入通道
        stockIn0-in-0:
          destination: stock-event-topic
          group: stock-db-consumer-group
          content-type: application/json
  #redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  #mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
