server:
  port: 8103

spring:
  application:
    name: mall-product-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        group: DEFAULT_GROUP
      config:
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml