server:
  port: 8102

spring:
  application:
    name: mall-order-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        group: DEFAULT_GROUP
      config:
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启下划线映射驼峰命名
  global-config:
    db-config:
      id-type: auto #主键id交给数据库自增
