server:
  port: 8102

spring:
  application:
    name: mall-order-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    function:
      definition: orderCreateIn0;orderPayIn0
    stream:
        rocketmq:
          binder:
            name-server: 127.0.0.1:9876
        bindings:
          orderCreateOut0:
            destination: order-create-topic
            content-type: application/json
          orderCreateIn0-in-0:
            destination: order-create-topic
            group: order-create-consumer-group
            content-type: application/json
          orderPayOut0:
            destination: order-pay-topic
            content-type: application/json
          orderPayIn0-in-0:
            destination: order-pay-topic
            group: order-pay-consumer-group
            content-type: application/json
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        group: DEFAULT_GROUP
      config:
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启下划线映射驼峰命名
  global-config:
    db-config:
      id-type: auto #主键id交给数据库自增
order:
  #未支付
  timeout-cancel:
    enabled: true
    fixed-delay: 60000 #60s执行一次
    minutes: 15
    limit: 200
    lock:
      name: order-timeout-cancel
      ttl: 120000 #120s过期
  #处理超时
  processing-timeout:
    enabled: true
    fixed-delay: 60000 #60s执行一次
    minutes: 15
    limit: 200
    lock:
      name: order-processing-timeout
      ttl: 120000 #120s过期
  pay-timeout:
    enabled: true
    fixed-delay: 60000 #60s执行一次
    minutes: 2
    limit: 200
    lock:
      name: order-pay-timeout
      ttl: 120000 #120s过期
